# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Bevegram' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bevegram
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # https://github.com/facebook/react-native-fbsdk/pull/353
  pod 'Bolts'
  pod 'react-native-fbsdk', :subspecs => [
    'Core',
    'Login',
    'Share',
  ], :path => '../node_modules/react-native-fbsdk/ios'

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  # react-native-firebase
  # Note: If the are problems building react native:
  # 1. Comment out the `RNFirebase` pod
  # 2. Run `pod install`
  # 3. Uncomment
  # 4. Run `pod install` again
  # See https://github.com/invertase/react-native-firebase/issues/278
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Crash'

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge',
    'Core',
  ]


  target 'BevegramTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Bevegram-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bevegram-tvOS

  target 'Bevegram-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# # Get archive builds working again
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end
