# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bevegram' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bevegram
  pod 'Firebase/Messaging'

  target 'BevegramTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Bevegram-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bevegram-tvOS

  target 'Bevegram-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
